/**
 * Regenerate wardrobe display images with Gemini — front and back.
 *
 * For each side: garment crop → Gemini product shot → transparency → thumbnail.
 * The originals (`front`/`back` and their crops) are never touched, and every
 * raw generation is archived, so a bad run is always recoverable.
 *
 * The catalog tile ALWAYS ends up showing the new generation (Dinesh, 2026-07-25:
 * "automatically replace the old cutout photo with the new regen image"). Best
 * available form wins, in order: model-native transparency → flat-key → ML
 * segmentation → keyed-but-imperfect → the generation flattened. Only a failed
 * generation leaves an item alone.
 *
 * Raw generations archive under data/generated/<itemId>/ (never served); the
 * servable copies are the `generated_front` / `generated_back` roles.
 *
 * VM-only by intent (Vertex credentials live there).
 *
 * Run: npx tsx scripts/regenerate-images.ts [--dry-run] [--only <itemId>]
 *          [--limit N] [--side front|back] [--missing] [--delay <ms>]
 *
 * `--missing` skips sides that already have a generation — that is the retry
 * flag after a partial run, and it never re-spends on work that succeeded.
 */
import path from "node:path";
import fs from "node:fs";
import { and, eq, ne } from "drizzle-orm";
import { loadEnvFile } from "../src/server/lib/env-file";

loadEnvFile(); // must precede anything that reads Vertex config

import { getDb, schema, dataDir } from "../src/server/db/client";
import { newId, nowIso } from "../src/server/lib/ids";
import {
  resolveImagePath,
  relativeImagePath,
  saveBuffer,
  sha256Of,
  itemImageDir,
} from "../src/server/imaging/storage";
import { makeThumbnail } from "../src/server/imaging/thumbnails";
import { cutoutFromGenerated, type Cutout } from "../src/server/imaging/cutout-ladder";
import { generateProductShot } from "../src/server/ai/image-generation";
import { hasVertexKey } from "../src/server/ai/vertex-client";

const db = getDb();

/** ~$0.04/image at current Gemini flash-image rates; for the dry-run estimate. */
const COST_PER_IMAGE = 0.04;

type Side = "front" | "back";

function imageRow(itemId: string, role: string) {
  return db
    .select()
    .from(schema.itemImages)
    .where(and(eq(schema.itemImages.itemId, itemId), eq(schema.itemImages.role, role as never)))
    .get();
}

function upsertImage(itemId: string, role: string, absPath: string, buffer: Buffer): void {
  const existing = imageRow(itemId, role);
  if (existing) {
    db.update(schema.itemImages)
      .set({ path: relativeImagePath(absPath), sha256: sha256Of(buffer), width: null, height: null })
      .where(eq(schema.itemImages.id, existing.id))
      .run();
  } else {
    db.insert(schema.itemImages)
      .values({
        id: newId(),
        itemId,
        role: role as never,
        path: relativeImagePath(absPath),
        sha256: sha256Of(buffer),
        createdAt: nowIso(),
      })
      .run();
  }
}

function setThumbnail(itemId: string, absPath: string, buffer: Buffer, w: number, h: number): void {
  const existing = imageRow(itemId, "thumbnail");
  if (existing) {
    db.update(schema.itemImages)
      .set({ path: relativeImagePath(absPath), width: w, height: h, sha256: sha256Of(buffer) })
      .where(eq(schema.itemImages.id, existing.id))
      .run();
  } else {
    upsertImage(itemId, "thumbnail", absPath, buffer);
  }
}

/** Has this side already been generated (and the file survived)? */
function alreadyGenerated(itemId: string, side: Side): boolean {
  const row = imageRow(itemId, `generated_${side}`);
  return !!row && fs.existsSync(resolveImagePath(row.path));
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

/** Best available source photo for a side: the tight crop, else the original. */
function sourcePhoto(itemId: string, side: Side): { buffer: Buffer; mime: string } | null {
  for (const role of [`${side}_cropped`, side]) {
    const row = imageRow(itemId, role);
    if (!row) continue;
    const abs = resolveImagePath(row.path);
    if (!fs.existsSync(abs)) continue;
    return {
      buffer: fs.readFileSync(abs),
      mime: abs.endsWith(".png") ? "image/png" : "image/jpeg",
    };
  }
  return null;
}

/** Repoint the catalog tile at freshly generated bytes. Always succeeds. */
async function refreshThumbnail(
  itemId: string,
  dir: string,
  cutout: Cutout | null,
  generated: Buffer,
): Promise<string> {
  if (cutout) {
    const thumb = await makeThumbnail(cutout.png, { alpha: true });
    const p = path.join(dir, "thumbnail.png");
    await saveBuffer(p, thumb.buffer);
    setThumbnail(itemId, p, thumb.buffer, thumb.width, thumb.height);
    return "transparent tile";
  }
  // No transparency at all: show the studio shot itself rather than keep a stale
  // tile. Flattened to JPEG on the app background like every other opaque tile.
  const thumb = await makeThumbnail(generated);
  const p = path.join(dir, "thumbnail.jpg");
  await saveBuffer(p, thumb.buffer);
  setThumbnail(itemId, p, thumb.buffer, thumb.width, thumb.height);
  return "opaque tile (no transparency available)";
}

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const arg = (flag: string) => {
    const i = args.indexOf(flag);
    return i >= 0 ? args[i + 1] : undefined;
  };
  const only = arg("--only");
  const limit = arg("--limit") ? Number(arg("--limit")) : undefined;
  const sideArg = arg("--side") as Side | undefined;
  const sides: Side[] = sideArg ? [sideArg] : ["front", "back"];
  const missingOnly = args.includes("--missing");
  // Image-model quota is per-minute; pacing costs a few minutes and avoids the
  // 429 storm that failed 10 of 24 images on the first full run.
  const delayMs = arg("--delay") ? Number(arg("--delay")) : 5_000;

  /** Sides worth attempting for an item, honouring --missing. */
  const todo = (itemId: string): Side[] =>
    sides.filter((s) => sourcePhoto(itemId, s) && !(missingOnly && alreadyGenerated(itemId, s)));

  if (!dryRun && !hasVertexKey()) {
    console.error("No Vertex credentials (expected VERTEX_USE_ADC=1 or a key in .env.local) — nothing to do.");
    process.exit(1);
  }

  let items = db.select().from(schema.items).where(ne(schema.items.state, "archived")).all();
  if (only) items = items.filter((i) => i.id === only);
  if (limit && limit > 0) items = items.slice(0, limit);

  if (dryRun) {
    let shots = 0;
    for (const item of items) {
      const present = todo(item.id);
      shots += present.length;
      console.log(
        `- ${item.name || item.id.slice(0, 8)}: ${present.length ? present.join(" + ") : "nothing to do"}`,
      );
    }
    console.log(
      `\n${items.length} item(s), ${shots} image(s) to generate — est. ~$${(shots * COST_PER_IMAGE).toFixed(2)} at $${COST_PER_IMAGE}/image`,
    );
    return;
  }

  console.log(`${items.length} item(s) × [${sides.join(", ")}]`);
  const generatedRoot = path.join(dataDir, "generated");
  let attempts = 0;
  let generated = 0;
  let clean = 0;
  let failed = 0;

  for (const item of items) {
    const label = item.name || item.id.slice(0, 8);
    const dir = itemImageDir(item.id);
    let frontCutout: Cutout | null = null;
    let frontGenerated: Buffer | null = null;

    const wanted = todo(item.id);
    if (wanted.length === 0) {
      console.log(`- ${label}: nothing to do`);
      continue;
    }

    for (const side of wanted) {
      const src = sourcePhoto(item.id, side)!;
      if (attempts > 0 && delayMs > 0) await sleep(delayMs);
      attempts++;

      const shot = await generateProductShot(src.buffer, src.mime);
      if (!shot) {
        failed++;
        console.log(`! ${label} (${side}): generation failed — left untouched`);
        continue;
      }
      generated++;

      // Archive the raw generation (provenance/history), never served.
      await saveBuffer(
        path.join(generatedRoot, item.id, `${side}-${sha256Of(shot.png).slice(0, 8)}.png`),
        shot.png,
      );

      const genPath = path.join(dir, `generated_${side}.png`);
      await saveBuffer(genPath, shot.png);
      upsertImage(item.id, `generated_${side}`, genPath, shot.png);

      const cutout = await cutoutFromGenerated(shot.png);
      if (cutout) {
        if (cutout.clean) clean++;
        const cutPath = path.join(dir, `transparent_${side}.png`);
        await saveBuffer(cutPath, cutout.png);
        upsertImage(item.id, `transparent_${side}`, cutPath, cutout.png);
      }
      console.log(
        `${cutout?.clean ? "✓" : "~"} ${label} (${side}): ${shot.model} · ${cutout ? cutout.how : "no transparency"}`,
      );

      if (side === "front") {
        frontCutout = cutout;
        frontGenerated = shot.png;
      }
    }

    // The tile follows the new front generation whenever we produced one.
    if (frontGenerated) {
      const how = await refreshThumbnail(item.id, dir, frontCutout, frontGenerated);
      console.log(`  → tile: ${how}`);
    }
  }

  console.log(
    `\nDone: ${generated} generated (${clean} clean cutouts), ${failed} failed. ` +
      `Est. spend ~$${(generated * COST_PER_IMAGE).toFixed(2)}.`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
